version: '2'

services:
    # App
    flask:
        build:
            context: .
        restart: always
        ports:
            - 5000:5000
        # Change this if you want to use a location on the host, or it will use a Docker volume.
        volumes:
            - .:/app
        links:
            - db:dbhost
        networks:
            - app-network
      # The database server.
    db:
      image: mysql:5.7
      container_name: db
      restart: always
      # Get environment variables from a file. Note: Open mysql.env to add your config.
      env_file:
        - mysql.env
      # Change this if you want to use a location on the host, or it will use a Docker volume.
      volumes:
        - db_data:/var/lib/mysql
      networks:
        - app-network
    # (Optional) A PHPMyAdmin web interface for the database.
    phpmyadmin:
      depends_on:
        - db
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
        - 8080:80
      links:
        - db:dbhost
      env_file:
        - mysql.env
      environment:
        PMA_HOST: db
      networks:
        - app-network

networks:
    app-network:
      driver: bridge

volumes:
  db_data:
